package com.brizy.io.web.test.enums;

public enum StorageKey {
    PLAYWRIGHT, BROWSER, CONTEXT, HOME_PAGE, DASHBOARD_PAGE, EDITOR, INIT_PAGE, PAGE_SECTIONS, ITEMS_TO_BE_ADDED_TO_THE_PAGE, EDITOR_PAGE, PUBLISH_PAGE, PROPERTY_TYPES
}
