package com.brizy.io.web.test.enums;

public enum StorageKey {
    PLAYWRIGHT, BROWSER, CONTEXT, HOME_PAGE, EDITOR, PAGE_SECTIONS, ITEMS_TO_BE_ADDED_TO_THE_PAGE, EDITOR_PAGE, PUBLISH_PAGE, COMPONENT_PROPERTIES, CURRENT_SCENARIO, CSS_EDITOR_COMPONENT_PROPERTIES, MENU_ITEMS, EDITOR_BOTTOM_PANEL_ITEMS, EDITOR_BOTTOM_PANEL_SAVE_MENU_ITEMS, PROPERTY_TYPES
}
