name: Verify merge requests and publish allure reports

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: maven

      - name: Run Test
        run: mvn -B -q compile install -DskipTests