name: Automatically run UI tests from foreign repo

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        required: true
        description: Preview Cloud url
        type: string
      repoPrId:
        required: false
        description: The foreign repo pr id
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_tests:
    runs-on: [ self-hosted, builder, office-server ]

    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: maven

      - name: Compile and install dependencies
        run: mvn -T 4C clean compile install -DskipTests

      - name: Download playwright dependencies
        run: mvn -T 4C exec:java -pl web-test -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

      - name: Run tests
        run: mvn -T 4C test -DbaseUrl=${{ github.event.inputs.baseUrl }} -Dcucumber.filter.tags=@Smoke

      - name: Get Allure history
        if: always()
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: allure-reports-history
          path: allure-reports-history

      - name: Check and clear allure history
        if: always()
        run: |
          mkdir -p ./allure-reports-history
          mkdir -p ./allure-history
          cp -r ./allure-reports-history/. ./allure-history

          echo "count folders in allure-history: $( ( ls ./allure-history | wc -l ) )"
          echo "keep reports count 20"
          echo "if $( ( ls ./allure-history | wc -l ) ) > 11"
          if (( $( ( ls ./allure-history | wc -l ) ) > 10+1 )); then
            cd ./allure-history
            echo "remove index.html last-history"
            rm index.html last-history -rv 2>/dev/null
            echo "remove old reports"
            ls | sort -n | head -n -$((10-5)) | xargs rm -rv 2>/dev/null
            cd ..
          fi

          echo "<!DOCTYPE html><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; URL=https://bagrinsergiu.github.io/brizy-atf/${{ github.run_number }}/\">" > ./allure-history/index.html # path
          echo "<meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\">" >> ./allure-history/index.html

      - name: Build executor properties
        if: always()
        run: |
          echo '{"name":"GitHub Actions","type":"github","reportName":"Brizy Regression run",' > executor.json
          echo "\"url\":\"https://bagrinsergiu.github.io/brizy-atf\"," >> executor.json # ???
          echo "\"reportUrl\":\"https://bagrinsergiu.github.io/brizy-atf/${{ github.run_number }}/\"," >> executor.json
          echo "\"buildUrl\":\"hhttps://github.com/bagrinsergiu/brizy-atf/actions/runs/${{ github.run_id }}\"," >> executor.json
          mv ./executor.json ./web-test/target/allure-results

      - name: Copy old history to recent allure results folder
        if: always()
        run: |
          cp -r ./gh-pages-main-branch/last-history/. ./web-test/target/allure-results/history 2>/dev/null        

      - name: Generate allure reports
        if: always()
        run: mvn -pl web-test allure:report

      - name: Copy allure results to publish directory
        if: always()
        run: |
          cp -r ./web-test/target/allure-report/. ./allure-history/${{ github.run_number }}
          echo "copy allure-report history to /allure-history/last-history"
          cp -r ./web-test/target/allure-report/history/. ./allure-history/last-history

      - name: Deploy reports to Github Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: allure-reports-history
          folder: allure-history
          force: true

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: './allure-history'

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.PERSONAL_TOKEN}}
          context: 'Test report'
          state: 'success'
          target_url: https://bagrinsergiu.github.io/brizy-atf/${{ github.run_number }}/index.html

#      - name: Attach Report to foreign repo
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          repo: blox-editor
#          number: ${{ github.event.inputs.repoPrId }}
#          message: |
#            E2E Report: https://bagrinsergiu.github.io/brizy-atf/${{ github.run_number }}/index.html
