name: Automatically run UI tests from foreign repo

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        required: true
        description: Preview Cloud url
        type: string

jobs:
  run_tests:
    runs-on: [ self-hosted, builder, office-server ]

    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: maven

      - name: Compile and install dependencies
        run: mvn clean compile install -DskipTests

      - name: Download playwright dependencies
        run: mvn exec:java -pl web-test -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

      - name: Run tests
        run: mvn test -DbaseUrl=${{ github.event.inputs.baseUrl }} -Dcucumber.filter.tags=@Test

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages-dev
          path: gh-pages-dev

      - name: Generate allure reports
        run: mvn -pl web-test allure:report

      - name: Copy allure results to publish directory
        run: cp -r ./web-test/target/allure-report allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages-dev
          PUBLISH_DIR: allure-history