name: Automatically run UI tests from foreign repo

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        required: true
        description: Preview Cloud url
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_tests:
    runs-on: [ self-hosted, builder, office-server ]

    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: maven

      - name: Compile and install dependencies
        run: mvn clean compile install -DskipTests

      - name: Download playwright dependencies
        run: mvn exec:java -pl web-test -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

      - name: Run tests
        run: mvn test -DbaseUrl=${{ github.event.inputs.baseUrl }} -Dcucumber.filter.tags=@Test

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure reports
        run: mvn -pl web-test allure:report

      #      - name: List files
      #        run:
      #          mv ./web-test/target/allure-report .

      - name: Copy allure results to publish directory
        run: |
          mkdir -p ./gh-pages
          mkdir -p ./allure-history
          cp -r ./gh-pages/. ./allure-history

          echo "count folders in allure-history: $( ( ls ./allure-history | wc -l ) )"
          echo "keep reports count 20"
          echo "if $( ( ls ./allure-history | wc -l ) ) > 21"
          if (( $( ( ls ./allure-history | wc -l ) ) > 21 )); then
          cd ./allure-history
          echo "remove index.html last-history"
          rm index.html last-history -rv
          echo "remove old reports"
          ls | sort -n | head -n -$((20-2)) | xargs rm -rv;
          cd ${GITHUB_WORKSPACE}
          fi

          echo "<!DOCTYPE html><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; URL=https://bagrinsergiu.github.io/brizy-atf/${{ github.run_number }}/\">" > ./allure-history/index.html # path
          echo "<meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\">" >> ./allure-history/index.html

          cp -r ./gh-pages/last-history/. ./web-test/target/allure-report/history

          cp -r ./web-test/target/allure-report/. ./allure-history/${{ github.run_number }}
          echo "copy allure-report history to /allure-history/last-history"
          cp -r ./web-test/target/allure-report/history/. ./allure-history/last-history

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './allure-history'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
#
#      - name: Deploy report to Github Pages
      #        uses: peaceiris/actions-gh-pages@v2
      #        env:
      #          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      #          PUBLISH_BRANCH: gh-pages
      #          PUBLISH_DIR: ./allure-history
      #
      #      - name: Get allure history content
      #        run: ls -a ./allure-history
      #
      - name: Post the link to the report
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.PERSONAL_TOKEN}}
          context: 'Test report'
          state: 'success'
          target_url: https://bagrinsergiu.github.io/brizy-atf/