name: Run regression pack of tests

on:
  schedule:
    - cron: '15 20 * * *'

jobs:
  run_tests:
    runs-on: [ self-hosted, builder, office-server ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: maven

      - name: Compile and install dependencies
        run: mvn clean compile install -DskipTests

      - name: Download playwright dependencies
        run: mvn exec:java -pl web-test -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

      - name: Run tests
        run: mvn test -DuseKiwi=true
